
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const LibraryItemSource = {
  google_photos: 'google_photos',
  instagram: 'instagram',
  other: 'other',
  pinterest: 'pinterest',
  tiktok: 'tiktok'
} as const

export type LibraryItemSource = (typeof LibraryItemSource)[keyof typeof LibraryItemSource]
